# Generated by Django 3.1.6 on 2021-03-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Pratos', 'Pratos'), ('Pizzas', 'Pizzas'), ('Massas', 'Massas'), ('Bebidas', 'Bebidas'), ('Salgados', 'Salgados'), ('Doces', 'Doces')], default='Pratos', max_length=30)),
                ('foto', models.ImageField(height_field='300', upload_to='cardapio', width_field='300')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
