# Generated by Django 3.1.6 on 2021-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='foto',
            field=models.ImageField(upload_to='cardapio'),
        ),
    ]
